### PR TITLE
Limit Stack Traces to Avoid Hitting LogDNA Limit

### PR DESCRIPTION
**Pull request by liamkeily**
We are hitting the LogDNA limit so i thought it may help if we can set a stack trace limit

### CODE REVIEW

**Comment by maxakropolis** [comment]
Do we still have the logic which excludes traces from certain folders?

**Comment by liamkeily** [comment]
@maxakropolis excluding files still exists

**Comment by maxakropolis** [comment]
@liamkeily Do you know if we're using it still?

**Comment by liamkeily** [comment]
@maxakropolis 

We seem to be https://github.com/fusionspim/fusions/blob/84b453f8e5de08167fa14c94eb4fe1a1b3caa052/config/logging/logging_all.php#L31

**Review by maxakropolis — APPROVED** [review]

**Pull request merged**
